// Generated by CoffeeScript 1.3.3
var ArgumentParser, action, argparse, args, parser, print;

print = console.log;

try {
  argparse = require('../lib/argparse');
} catch (error) {
  argparse = require('argparse');
}

ArgumentParser = argparse.ArgumentParser;

parser = new ArgumentParser({
  debug: true
});

parser.addArgument(['-c'], {
  dest: '-c',
  choice: ['0', '*', '?'],
  defaultValue: '0'
});

parser.addArgument(['-x', '--xxx'], {
  action: 'storeTrue'
});

parser.addArgument(['-y'], {
  dest: 'yyy',
  nargs: 1
});

parser.addArgument(['-z', '--zzz'], {
  action: 'storeTrue'
});

parser.addArgument(['-d'], {
  dest: 'd',
  defaultValue: 'DEFAULT'
});

parser.printHelp();

args = parser.parseArgs([]);

print('defaults', args);

print('parser.getDefaults(dest) test');

print((function() {
  var _i, _len, _ref, _results;
  _ref = parser._actions;
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    action = _ref[_i];
    _results.push("" + action.dest + ": " + (parser.getDefault(action.dest)));
  }
  return _results;
})());

print('positional defaults test');

parser = new ArgumentParser({
  debug: true,
  description: 'positional with 0 defaultValue'
});

parser.addArgument(['pos'], {
  type: 'int',
  nargs: '?',
  defaultValue: 0
});

print(parser.description, 'should be {pos: 0}');

print(parser.parseArgs([]));

parser = new ArgumentParser({
  debug: true,
  description: 'positional with ? nargs'
});

parser.addArgument(['pos'], {
  nargs: '?',
  defaultValue: 42
});

print(parser.description, 'should be {pos:42}');

print(parser.parseArgs([]));

parser = new ArgumentParser({
  debug: true,
  description: 'positional with * nargs'
});

parser.addArgument(['pos'], {
  nargs: '*',
  defaultValue: 42
});

print(parser.description, 'should be {pos:42}');

print(parser.parseArgs([]));
